### Options
OPTIONS {{u}}/darts
###

POST {{u}}/api/darts
Content-Type: application/json

{
  "module": "cowsay",
  "version": "v0.1.3",
  "inputs": {
    "Message": "Hi from vite dev "
  }
}

HTTP/1.1 500  - Internal Server Error
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch
content-type: application/json
date: Thu, 27 Feb 2025 01:42:39 GMT
connection: close
transfer-encoding: chunked
###

POST {{u}}/api/darts
Content-Type: application/json
###

POST {{ideo}}/darts
Content-Type: application/json

{
  "module": "cowsay",
  "version": "v0.1.3",
  "inputs": {
    "Message": "Hi from vite dev "
  }
}

HTTP/1.1 500  - Internal Server Error
date: Mon, 03 Mar 2025 15:54:46 GMT
content-type: application/json
content-length: 1037
connection: close
access-control-allow-origin: *
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=87gJdkrBoWvPrHgvNhmq16IoZAqGOeqOUGsa87ko0YqKL7xGaV63jNuZvRgaA2fHQkcblmK4aEPktqOo7ebi7cIF42GYE2KXI2iTvm9EejyPfX3Hko3Ky5DG1mvnPHS%2BpoSRbkoQcF0ilw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 91aa50241c02f940-MXP
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=200661&min_rtt=199893&rtt_var=76496&sent=5&recv=5&lost=0&retrans=0&sent_bytes=2819&recv_bytes=901&delivery_rate=19627&cwnd=249&unsent_bytes=0&cid=421bfcc1cba1b6e3&ts=14222&x=0"
###
POST {{u}}/darts
Authorization: Bearer 0xa618896c28db371a21f9d805c25e622425319d85684a1f9478568509a3f3f4a9
Content-Type: application/json

{
  "module": "cowsay",
  "version": "v0.1.3",
  "inputs": {
    "Message": "Hi from vite dev "
  }
}

HTTP/1.1 500  - Internal Server Error
access-control-allow-origin: *
content-length: 144
content-type: application/json
date: Sun, 12 Jan 2025 20:41:15 GMT
connection: close
###
POST {{u}}/darts
Authorization: Bearer 0xa618896c28db371a21f9d805c25e622425319d85684a1f9478568509a3f3f4a9
Content-Type: application/json

{
  "module": "github.com/darts2024/dart-isdxl",
  "version": "v1.6.0",
  "inputs": {
    "Prompt": "Beautiful girl",
    "Device": "xpu",
    "cpu": "20",
    "ram": "22gb",
    "Seed": "{{$randomInt 1 10000000}}",
    "N":1
  },
  "author": "e260b0ab-9867-4507-97be-976779c20c9f"
}

HTTP/1.1 404  - Not Found
cache-control: no-store, must-revalidate
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch, Accept-Encoding
x-powered-by: Next.js
content-type: text/html; charset=utf-8
content-encoding: gzip
date: Thu, 27 Feb 2025 02:05:32 GMT
connection: close
transfer-encoding: chunked
###

POST {{u}}/darts
Content-Type: application/json

{
  "module": "github.com/darts2024/dart-isdxl",
  "version": "v1.3.0",
  "inputs": {
    "Prompt": "Beautiful girl",
    "Device": "xpu",
    "Seed": "{{$randomInt 1 10000000}}"
  }
}

HTTP/1.1 500  - Internal Server Error
access-control-allow-origin: *
content-length: 204
content-type: application/json
date: Sun, 12 Jan 2025 20:42:37 GMT
connection: close
###

POST {{u}}/api/darts
Authorization: Bearer 0xa618896c28db371a21f9d805c25e622425319d85684a1f9478568509a3f3f4a9
Content-Type: application/json

{
  "module": "github.com/darts2024/dart-isdxl",
  "version": "v1.6.0",
  "inputs": {
    "Prompt": "Beautiful girl",
    "Device": "xpu",
    "Seed": "{{$randomInt 1 10000000}}"
  }
}

HTTP/1.1 200  - OK
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch
content-type: application/json
date: Thu, 27 Feb 2025 02:45:23 GMT
connection: close
transfer-encoding: chunked
###

POST {{u}}/api/darts
Content-Type: application/json

{
  "module": "cowsay",
  "version": "v0.1.3",
  "inputs": {
    "Message": "Hi from vite dev "
  }
}

HTTP/1.1 500  - Internal Server Error
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch
content-type: application/json
date: Thu, 27 Feb 2025 02:07:10 GMT
connection: close
transfer-encoding: chunked